"""Добавлены foreignKey в Tools и Parentid в Category

Revision ID: 03cc9d417bb6
Revises: 
Create Date: 2019-04-20 20:54:57.754405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cc9d417bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_categoryid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_categoryid'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Category_parent_categoryid'), ['parent_categoryid'], unique=False)

    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('gender', webapp.model.ChoiceType(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', webapp.model.ChoiceType(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_role'), ['role'], unique=False)

    op.create_table('Tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Tool_categoryid'), ['categoryid'], unique=False)

    op.create_table('Announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_id', webapp.model.ChoiceType(), nullable=False),
    sa.Column('head', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('pub_datetime', sa.DateTime(), nullable=False),
    sa.Column('arch_datetime', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['Tool.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Announcement_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_Announcement_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Announcement_type_id'), ['type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Announcement_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Announcement_user_id'))
        batch_op.drop_index(batch_op.f('ix_Announcement_type_id'))
        batch_op.drop_index(batch_op.f('ix_Announcement_tool_id'))
        batch_op.drop_index(batch_op.f('ix_Announcement_address'))

    op.drop_table('Announcement')
    with op.batch_alter_table('Tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tool_categoryid'))

    op.drop_table('Tool')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_role'))
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.drop_index(batch_op.f('ix_User_address'))
        batch_op.drop_index(batch_op.f('ix_User_active'))

    op.drop_table('User')
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Category_parent_categoryid'))

    op.drop_table('Category')
    # ### end Alembic commands ###
